create database m4rk0;
use m4rk0;

-- OK
create table funcionario (
	CODIGO INT NOT NULL AUTO_INCREMENT,
	LOGIN VARCHAR(128) NOT NULL,
	SENHA VARCHAR(128) NOT NULL,
	PRIMARY KEY(CODIGO)
);

insert into funcionario (LOGIN, SENHA) values ("admin", "123");

-- OK
create table fornecedor (
	CODIGO INT NOT NULL AUTO_INCREMENT,
	RAZAO_SOCIAL VARCHAR(128) NOT NULL,
	CNPJ VARCHAR(128) NOT NULL,
	ENDERECO VARCHAR(128) NOT NULL,
	FONE VARCHAR(128) NOT NULL,
	FAX VARCHAR(128) NOT NULL,
	REPRESENTANTE VARCHAR(128) NOT NULL,
	PRIMARY KEY(CODIGO)
);

-- OK
create table cliente (
	CODIGO INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(128) NOT NULL,
	CPF VARCHAR(128) NOT NULL,
	ENDERECO VARCHAR(128) NOT NULL,
	FONE VARCHAR(128),
	CEL VARCHAR(128) NOT NULL,
	EMAIL VARCHAR(128) NOT NULL,
	PRIMARY KEY(CODIGO)
);

create table vendas (
	CODIGO_VENDA INT NOT NULL AUTO_INCREMENT,
	CLIENTE INT NOT NULL ,
	VENDEDOR INT NOT NULL ,
	HORARIO DATETIME NOT NULL,
	PRIMARY KEY(CODIGO_VENDA)
);

create table item_pedido (
	VENDA INT NOT NULL,
	CODIGO_PRODUTO INT NOT NULL,
	DESCRICAO VARCHAR(128) NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALOR_UNITARIO DOUBLE NOT NULL,
	VALOR_TOTAL DOUBLE NOT NULL
);

-- OK
create table produto (
	CODIGO INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(128) NOT NULL, 
	DESCRICAO VARCHAR(128) NOT NULL, 
	QUANTIDADE INT NOT NULL, 
	DATA_DE_COMPRA DATETIME NOT NULL, 
	VENCIMENTO DATETIME NOT NULL, 
	CUSTO DOUBLE NOT NULL, 
	PRECO_DE_VENDA DOUBLE NOT NULL,
	PRIMARY KEY(CODIGO)	
);

-- OK
create table despesas (
	CODIGO_CONTA INT NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(128) NOT NULL, 
	CREDOR VARCHAR(128) NOT NULL, 
	VALOR DOUBLE NOT NULL,
	LANCAMENTO DATETIME NOT NULL, 
	VENCIMENTO DATETIME NOT NULL,
	PRIMARY KEY(CODIGO_CONTA)
);
